SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `management` ;
CREATE SCHEMA IF NOT EXISTS `management` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `management` ;

commit; 