drop table if exists df_task;
drop table if exists df_user;

create table df_task (
	id bigint generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table df_user (
	id bigint generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,
	register_date timestamp not null,
	primary key (id)
);


--just a test start
drop table if exists df_book;

create table df_book (
	id bigint auto_increment,
	title varchar(128) not null,
	description varchar(255),
	publish_date timestamp not null ,
	price decimal(10,2) not null default 0.00,
	primary key (id)
);
--just a test end


    drop table if exists df_admin_role;

    drop table if exists df_role;

    drop table if exists df_admin;
    
    drop table if exists df_team;

    create table df_role (
        id bigint generated by default as identity,
    	name varchar(255) not null unique,
    	permissions varchar(255),
        primary key (id)
    );

    create table df_admin (
       	id bigint generated by default as identity,
        login_name varchar(255) not null unique,
        name varchar(64),
        password varchar(255),
        salt varchar(64),
        email varchar(128),
        status varchar(32),
        team_id bigint,
        primary key (id)
    );

    create table df_admin_role (
        admin_id bigint not null,
        role_id bigint not null,
        primary key (admin_id, role_id)
    );
    
   	create table df_team (
       	id bigint generated by default as identity,
    	name varchar(255) not null unique,
    	master_id bigint,
        primary key (id)
    );